name: Deploy Astro site to Pages

on:
  push:
    branches: ["main", "feat/migracion-a-root"] # <-- Ahora también se activará en esta rama

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Astro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: minor-mercury # <-- Busca el package.json aquí adentro

      - name: Build Astro
        run: pnpm run build
        working-directory: minor-mercury # <-- Ejecuta el build aquí adentro

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./minor-mercury/dist # <-- Sube la carpeta dist que se generó dentro de minor-mercury

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4